export const Routes = {
    WelcomeScreen: "WelcomeScreen",
    LoginScreen: "LoginScreen",
    ForgetPasswordPage: "ForgetPasswordPage",
    RegisterScreen: "RegisterScreen",
    ForgetPasswordOTPVerificationScreen: "ForgetPasswordOTPVerificationScreen",
    RegistrationOTPVerificationScreen: "RegistrationOTPVerificationScreen",
    CreateNewPasswordPageScreen: "CreateNewPasswordPageScreen",
    PasswordChangedScreen: 'PasswordChangedScreen',
    HomePage: "HomePage",
    DashboardScreen: "DashboardScreen",
    AppUsageScreen: "AppUsageScreen",
    DetailedAppUsageScreen: "DetailedAppUsageScreen",
    ProfileScreen: "ProfileScreen",
};
