export const Routes = {
    WelcomeScreen: "WelcomeScreen",
    LoginScreen: "LoginScreen",
    ForgetPasswordPage: "ForgetPasswordPage",
    RegisterScreen: "RegisterScreen",
    AvatarUploadScreen: "AvatarUploadScreen",
    PhotoUploadScreen: "PhotoUploadScreen",
    OTPVerificationScreen: "OTPVerificationScreen",
    EditProfileScreen: "EditProfileScreen",
    ProfilePreviewScreen: "ProfilePreviewScreen",
    ProfileSettingScreen: "ProfileSettingScreen",
    ForgetPasswordOTPVerificationScreen: "ForgetPasswordOTPVerificationScreen",
    RegistrationOTPVerificationScreen: "RegistrationOTPVerificationScreen",
    CreateNewPasswordPageScreen: "CreateNewPasswordPageScreen",
    PasswordChangedScreen: 'PasswordChangedScreen',
    HomePage: "HomePage",
    DashboardScreen: "DashboardScreen",
    AppUsageScreen: "AppUsageScreen",
    DetailedAppUsageScreen: "DetailedAppUsageScreen",
    ProfileScreen: "ProfileScreen",
    ProfileUpdatedScreen: "ProfileUpdatedScreen",
    AppLimitsScreen: 'AppLimitsScreen',
    PasswordResetLinkSentSuccessfullyScreen: "PasswordResetLinkSentSuccessfullyScreen",
    CreateUsernameScreen: "CreateUsernameScreen",
};
