export const Routes = {
    WelcomeScreen: "WelcomeScreen",
    LoginScreen: "LoginScreen",
    ForgetPasswordPage: "ForgetPasswordPage",
    RegisterScreen: "RegisterScreen",
    AvatarUploadScreen: "AvatarUploadScreen",
    OTPVerificationScreen: "OTPVerificationScreen",
    EditProfileScreen: "EditProfileScreen",
    ProfilePreviewScreen: "ProfilePreviewScreen",
    ProfileSettingScreen: "ProfileSettingScreen",
    ForgetPasswordOTPVerificationScreen: "ForgetPasswordOTPVerificationScreen",
    RegistrationOTPVerificationScreen: "RegistrationOTPVerificationScreen",
    CreateNewPasswordScreen: "CreateNewPasswordScreen",
    PasswordChangedScreen: 'PasswordChangedScreen',
    DashboardScreen: "DashboardScreen",
    AppUsageScreen: "AppUsageScreen",
    DetailedAppUsageScreen: "DetailedAppUsageScreen",
    ProfileScreen: "ProfileScreen",
    ProfileUpdatedScreen: "ProfileUpdatedScreen",
    AppLimitsScreen: 'AppLimitsScreen',
    PasswordResetLinkSentSuccessfullyScreen: "PasswordResetLinkSentSuccessfullyScreen",
    CreateUsernameScreen: "CreateUsernameScreen",
    CreateAnAccount: "CreateAnAccount",
    MainDashboardScreen: "MainDashboardScreen",
};
